[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[history.headers]
  for = "/*"
  [history.headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"